AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for view counter backend with API Gateway, Lambda, and DynamoDB

Parameters:
  TableName:
    Type: String
    Description: Name of the DynamoDB table
  FunctionName:
    Type: String
    Description: Name of the Lambda function
  WebPageOrigin:
    Type: String
    Description: Origin hosting the webpage making calls to ViewCounter endpoint. Used of OAC validation.
  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID
  CertificateArn:
    Type: String
    Description: ARN of the ACM certificate for the custom domain
  ViewCounterApiDomain:
    Type: String
    Description: Custom domain name for the View Counter API

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    Environment:
      Variables:
        TABLE_NAME: !Ref ViewCounterTable
        WEB_PAGE_ORIGIN: !Ref WebPageOrigin

Resources:
  ViewCounterTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: page_id
          AttributeType: S
      KeySchema:
        - AttributeName: page_id
          KeyType: HASH

  ViewCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: functions/
      Handler: view-counter-function.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ViewCounterTable
      Events:
        GetViewCount:
          Type: Api
          Properties:
            RestApiId: !Ref ViewCounterApi
            Path: /views/{page_id}
            Method: GET
        UpdateViewCount:
          Type: Api
          Properties:
            RestApiId: !Ref ViewCounterApi
            Path: /views/{page_id}
            Method: POST

  ViewCounterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      TracingEnabled: true
      DisableExecuteApiEndpoint: true
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          ThrottlingBurstLimit: 10
          ThrottlingRateLimit: 5
      Auth:
        DefaultAuthorizer: NONE
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
              Access-Control-Allow-Headers: "'Content-Type,Authorization'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
              Access-Control-Allow-Headers: "'Content-Type,Authorization'"

  ViewCounterApiCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref ViewCounterApiDomain
      RegionalCertificateArn: !Ref CertificateArn
      EndpointConfiguration:
        Types:
          - REGIONAL

  ViewCounterApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref ViewCounterApiCustomDomain
      RestApiId: !Ref ViewCounterApi
      Stage: prod

  ViewCounterApiDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ViewCounterApiDomain
      Type: A
      AliasTarget:
        DNSName: !GetAtt ViewCounterApiCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt ViewCounterApiCustomDomain.RegionalHostedZoneId
