AWSTemplateFormatVersion: "2010-09-09"
Description: Backend prerequisites infrastructure for SAM deployments (artifact bucket)

Parameters:
  ArtifactBucketName:
    Type: String
    Description: Name of the S3 bucket for SAM deployment artifacts

Resources:
  SAMArtifactBucket:
    Type: AWS::S3::Bucket
    Metadata:
      guard:
        SuppressedRules:
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_VERSIONING_ENABLED
    Properties:
      BucketName: !Ref ArtifactBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
