AWSTemplateFormatVersion: "2010-09-09"
Description: S3 bucket for static website hosting

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Metadata:
      guard:
        SuppressedRules:
          - S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED
          - S3_BUCKET_PUBLIC_READ_PROHIBITED
          - S3_BUCKET_PUBLIC_WRITE_PROHIBITED
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_VERSIONING_ENABLED

    Properties:
      BucketName: !Sub "${AWS::StackName}-bucket"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${S3Bucket.Arn}/*"
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "${S3Bucket.Arn}/*"
              - !GetAtt S3Bucket.Arn
            Condition:
              Bool:
                aws:SecureTransport: false

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket

  WebsiteURL:
    Description: URL of the website
    Value: !GetAtt S3Bucket.WebsiteURL
