AWSTemplateFormatVersion: "2010-09-09"
Description: S3 bucket for static website hosting
Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket
  CustomDomain:
    Type: String
    Description: Custom domain name (e.g., borisatudn.online)
    Default: ""
  HostedZoneId:
    Type: String
    Description: Route 53 hosted zone ID that serves the CustomDomain
    Default: ""
Conditions:
  HasCustomDomain: !And
    - !Not [!Equals [!Ref CustomDomain, ""]]
    - !Not [!Equals [!Ref HostedZoneId, ""]]
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Metadata:
      guard:
        SuppressedRules:
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_VERSIONING_ENABLED

    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontReadOAC
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: "s3:GetObject"
            Resource: !Sub "${S3Bucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "${S3Bucket.Arn}/*"
              - !GetAtt S3Bucket.Arn
            Condition:
              Bool:
                aws:SecureTransport: false

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${BucketName}-oac"
        Description: Origin Access Control for S3 bucket
        OriginAccessControlOriginType: s3
        SigningProtocol: sigv4
        SigningBehavior: always

  ACMCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: HasCustomDomain
    Properties:
      DomainName: !Ref CustomDomain
      SubjectAlternativeNames:
        - !Sub "www.${CustomDomain}"
      DomainValidationOptions:
        - DomainName: !Ref CustomDomain
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub "www.${CustomDomain}"
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "CloudFront distribution for ${BucketName}"
        DefaultRootObject: index.html
        Aliases:
          - !If [HasCustomDomain, !Ref CustomDomain, !Ref "AWS::NoValue"]
          - !If [
              HasCustomDomain,
              !Sub "www.${CustomDomain}",
              !Ref "AWS::NoValue",
            ]
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt S3Bucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref OriginAccessControl
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # AWS-managed "CachingOptimized" policy
        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: /index.html
            ResponseCode: "200"
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponsePagePath: /index.html
            ResponseCode: "200"
            ErrorCachingMinTTL: 300
        ViewerCertificate: !If
          - HasCustomDomain
          - AcmCertificateArn: !Ref ACMCertificate
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true

Outputs:
  CloudFrontDistributionId:
    Description: CloudFront distribution ID
    Value: !Ref CloudFrontDistribution

  CloudFrontDistributionArn:
    Description: CloudFront distribution ARN
    Value: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  CloudFrontDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName
